version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mariadb:10.6
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./backend/.env
    ports:
      - 3307:3306

volumes:
  mariadb_data:
